version: '3.8'

services:
  lab_app:
    build: ./lab_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lab_app/:/usr/src/lab_app/
    ports:
      - 8000:8000
    env_file:
      - ./lab_app/.env
    depends_on:
      - db
  db:
    container_name: lab_db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=lab
      - POSTGRES_DB=lab
    expose:
      - 5432
    ports:
      - "5435:5432"

volumes:
  postgres_data: